"""
Tests for scripts/install.py wizard.

Strategy: rich is a real dependency (dev extra). import install does NOT trigger
_maybe_install_rich(). We mock only interactive prompts and subprocess runners.
"""

import sys
from pathlib import Path
from unittest.mock import MagicMock

import pytest

import install


@pytest.fixture(autouse=True)
def _silence_console():
    """Silence console output — the real Console is used, just suppress."""
    install.console = MagicMock()


# ============================================================================
# Pure functions
# ============================================================================


class TestCheckCmd:
    def test_finds_system_command(self):
        cmd = "cmd" if sys.platform == "win32" else "ls"
        assert install._check_cmd(cmd)

    def test_not_found(self):
        assert not install._check_cmd("comando_que_no_existe_xyz123")


class TestIsInRepo:
    def test_inside_repo(self, tmp_path, monkeypatch):
        repo = tmp_path / "repo"
        repo.mkdir()
        (repo / "pyproject.toml").write_text(
            '[project]\nname = "opengrab"\n', encoding="utf-8"
        )
        subdir = repo / "subdir"
        subdir.mkdir()
        monkeypatch.chdir(subdir)
        assert install._is_in_repo() == repo

    def test_outside_repo(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        assert install._is_in_repo() is None

    def test_wrong_project_name(self, tmp_path, monkeypatch):
        repo = tmp_path / "not_opengrab"
        repo.mkdir()
        (repo / "pyproject.toml").write_text(
            '[project]\nname = "other-project"\n', encoding="utf-8"
        )
        monkeypatch.chdir(repo)
        assert install._is_in_repo() is None


class TestWriteEnvFile:
    def test_creates_env_file(self, tmp_path):
        config = {
            "OPENGRAB_TOKEN": "secret123",
            "OPENGRAB_PORT": "8080",
            "OPENGRAB_DIR": "/tmp/downloads",
            "OPENGRAB_MAX_JOBS": "4",
            "OPENGRAB_MAX_TOTAL_MB": "500",
            "OPENGRAB_AUTOUPDATE": "1",
        }
        install._write_env_file(tmp_path, config)

        env_path = tmp_path / ".env"
        assert env_path.exists()
        content = env_path.read_text(encoding="utf-8")
        assert "OPENGRAB_TOKEN=secret123" in content
        assert "OPENGRAB_PORT=8080" in content
        assert "OPENGRAB_DIR=/tmp/downloads" in content
        assert "OPENGRAB_MAX_JOBS=4" in content
        assert "OPENGRAB_MAX_TOTAL_MB=500" in content
        assert "OPENGRAB_AUTOUPDATE=1" in content
        assert "# Generated by install.py" in content

    def test_backs_up_existing_env(self, tmp_path):
        env_path = tmp_path / ".env"
        env_path.write_text("OLD_CONTENT", encoding="utf-8")

        config = {"OPENGRAB_TOKEN": "new_token"}
        install._write_env_file(tmp_path, config)

        backup = tmp_path / ".env.bak"
        assert backup.exists(), (
            f"Expected backup at {backup}, got contents: "
            + ", ".join(p.name for p in tmp_path.iterdir())
        )
        assert backup.read_text(encoding="utf-8") == "OLD_CONTENT"


class TestInstallSystemd:
    def test_with_venv(self, tmp_path, monkeypatch):
        monkeypatch.setattr(Path, "home", lambda: tmp_path)
        repo = tmp_path / "repo"
        repo.mkdir()
        venv = tmp_path / "venv"
        venv.mkdir()

        install._install_systemd(repo, venv, {"OPENGRAB_TOKEN": "tok", "OPENGRAB_PORT": "8800"})

        unit_path = tmp_path / ".config" / "systemd" / "user" / "opengrab.service"
        assert unit_path.exists()
        content = unit_path.read_text()
        assert f"ExecStart={venv / 'bin' / 'python'} app.py" in content
        assert f"WorkingDirectory={repo}" in content
        assert "Environment=OPENGRAB_TOKEN=tok" in content
        assert "Environment=OPENGRAB_PORT=8800" in content

    def test_without_venv(self, tmp_path, monkeypatch):
        monkeypatch.setattr(Path, "home", lambda: tmp_path)
        repo = tmp_path / "repo"
        repo.mkdir()

        install._install_systemd(repo, None, {"OPENGRAB_TOKEN": "tok"})

        unit_path = tmp_path / ".config" / "systemd" / "user" / "opengrab.service"
        content = unit_path.read_text()
        assert f"ExecStart={sys.executable} app.py" in content


class TestConfigureEnv:
    def test_defaults_no_custom_token(self, monkeypatch):
        """All confirms False, all prompts accept defaults."""
        monkeypatch.setattr(install.Confirm, "ask", lambda *a, **kw: False)
        monkeypatch.setattr(
            install.IntPrompt, "ask", lambda *a, **kw: int(kw.get("default", 0))
        )
        monkeypatch.setattr(
            install.Prompt, "ask", lambda *a, **kw: kw.get("default", "")
        )

        result = install._configure_env()

        assert result["OPENGRAB_MAX_JOBS"] == "2"
        assert result["OPENGRAB_MAX_TOTAL_MB"] == "0"
        assert result["OPENGRAB_AUTOUPDATE"] == "0"
        assert len(result["OPENGRAB_TOKEN"]) >= 16

    def test_custom_token(self, monkeypatch):
        monkeypatch.setattr(
            install.Confirm, "ask", MagicMock(side_effect=[True, False, False])
        )
        monkeypatch.setattr(
            install.IntPrompt,
            "ask",
            MagicMock(side_effect=[9999, 4]),
        )
        monkeypatch.setattr(
            install.Prompt,
            "ask",
            MagicMock(side_effect=["my-secret-token", "/custom/downloads"]),
        )

        result = install._configure_env()

        assert result["OPENGRAB_TOKEN"] == "my-secret-token"
        assert result["OPENGRAB_PORT"] == "9999"
        assert result["OPENGRAB_MAX_JOBS"] == "4"
        assert result["OPENGRAB_DIR"] == "/custom/downloads"
        assert result["OPENGRAB_MAX_TOTAL_MB"] == "0"
        assert result["OPENGRAB_AUTOUPDATE"] == "0"

    def test_with_disk_budget(self, monkeypatch):
        monkeypatch.setattr(
            install.Confirm, "ask", MagicMock(side_effect=[False, True, False])
        )
        monkeypatch.setattr(
            install.IntPrompt,
            "ask",
            MagicMock(side_effect=[8800, 2, 2048]),
        )
        monkeypatch.setattr(
            install.Prompt, "ask", lambda *a, **kw: kw.get("default", "")
        )

        result = install._configure_env()

        assert result["OPENGRAB_MAX_TOTAL_MB"] == "2048"
        assert result["OPENGRAB_MAX_JOBS"] == "2"
        assert result["OPENGRAB_AUTOUPDATE"] == "0"
        assert len(result["OPENGRAB_TOKEN"]) >= 16


# ============================================================================
# Flow tests — mode functions
# ============================================================================


class TestModeDocker:
    def test_happy_path(self, tmp_path, monkeypatch):
        repo = tmp_path / "opengrab"
        repo.mkdir()

        monkeypatch.setattr(install, "_check_cmd", lambda name: True)
        monkeypatch.setattr(install, "_is_in_repo", lambda: repo)
        monkeypatch.setattr(
            install,
            "_configure_env",
            lambda *a, **kw: {"OPENGRAB_PORT": "8800", "OPENGRAB_TOKEN": "tok"},
        )
        monkeypatch.setattr(install, "_write_env_file", MagicMock())
        monkeypatch.setattr(install, "_run_live", lambda *a, **kw: (0, "ok"))

        install._mode_docker()

    def test_missing_docker(self, tmp_path, monkeypatch):
        monkeypatch.setattr(install, "_check_cmd", lambda name: name not in ("docker", "docker-compose"))
        monkeypatch.setattr(install, "_status_table", MagicMock())
        monkeypatch.setattr(install, "_panel", MagicMock(return_value=MagicMock()))

        install._mode_docker()


class TestModeBaremetal:
    def test_happy_path_with_venv(self, tmp_path, monkeypatch):
        repo = tmp_path / "opengrab"
        repo.mkdir()

        monkeypatch.setattr(install, "_check_cmd", lambda name: True)
        monkeypatch.setattr(install, "_check_python", lambda: True)
        monkeypatch.setattr(install, "_is_in_repo", lambda: repo)
        monkeypatch.setattr(install, "_run", lambda *a, **kw: (0, "ok"))
        monkeypatch.setattr(
            install.Confirm, "ask", MagicMock(side_effect=[True, False])
        )
        monkeypatch.setattr(
            install,
            "_configure_env",
            lambda *a, **kw: {"OPENGRAB_PORT": "8800", "OPENGRAB_TOKEN": "tok"},
        )
        monkeypatch.setattr(install, "_write_env_file", MagicMock())

        install._mode_baremetal()

    def test_missing_python(self, monkeypatch):
        monkeypatch.setattr(install, "_check_cmd", lambda name: False)
        monkeypatch.setattr(install, "_check_python", lambda: False)

        install._mode_baremetal()


class TestModeDesktop:
    def test_happy_path(self, tmp_path, monkeypatch):
        repo = tmp_path / "opengrab"
        repo.mkdir()

        monkeypatch.setattr(install, "_check_cmd", lambda name: True)
        monkeypatch.setattr(install, "_check_python", lambda: True)
        monkeypatch.setattr(install, "_is_in_repo", lambda: repo)
        monkeypatch.setattr(install, "_run", lambda *a, **kw: (0, "ok"))
        monkeypatch.setattr(install, "_run_live", lambda *a, **kw: (0, "ok"))
        monkeypatch.setattr(install.Confirm, "ask", MagicMock(return_value=False))

        install._mode_desktop()

    def test_missing_python_and_pip(self, monkeypatch):
        monkeypatch.setattr(install, "_check_cmd", lambda name: False)
        monkeypatch.setattr(install, "_check_python", lambda: False)

        install._mode_desktop()
